[project]
name = "odoo-addons-oca-automation"
version = "18.0.20250725.0"
dependencies = [
    "odoo-addon-automation_oca==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
